ccf/urls.py
from django.conf import settings
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin
from django.urls import include
from django.urls import path
from django.urls import re_path
from two_factor.admin import AdminSiteOTPRequired
from two_factor.urls import urlpatterns as tf_urls

import app_ccf
from app_ccf.views import DASTStagingView
from app_ccf.views import LanguageView
#  from django.views.generic import RedirectView

handler400 = app_ccf.views.UnknownErrorView.get_rendered_view(status_code=400)
handler403 = app_ccf.views.UnknownErrorView.get_rendered_view(status_code=403)
handler404 = app_ccf.views.UnknownErrorView.get_rendered_view(status_code=404)
handler500 = app_ccf.views.ServerErrorView.get_rendered_view(status_code=500)

admin.site.__class__ = AdminSiteOTPRequired

ccfpatterns = [
    re_path(
        r'^(?P<accesscode>([a-zA-Z]{3}-[a-zA-Z]{3}-[a-zA-Z]{3}))/$',
        LanguageView.as_view(),
        name='language'
    ),
    path('', LanguageView.as_view(), name='language'),
    path('language', LanguageView.as_view(), name='language'),
    path('GitLab-DAST-Site-Validation-17640645-2256-4bca-a59f-982e79787585.txt', DASTStagingView.as_view(), name='staging-dast')
]

ccfpatterns += i18n_patterns(
    path('', include('app_ccf.urls')),
)

staffpatterns = [
    path('', include('staff.urls')),
    path('ssa/', admin.site.urls),
    path('accounts/', include('admin_honeypot.urls')),
    path('mfa/', include(tf_urls)),
]

urlpatterns = [
    path('i18n/', include('django.conf.urls.i18n')),
    path('session_security/', include('session_security.urls')),
]
# Based on app type variable, set urlpatterns
if settings.APP_TYPE == 'CCF':
    urlpatterns += ccfpatterns
elif settings.APP_TYPE == 'STAFF':
    urlpatterns += staffpatterns
else:  # Local/demo have access to staff urls directly from '/staff/'
    urlpatterns += ccfpatterns
    urlpatterns += [
        path('staff/', include(staffpatterns))
    ]

# https://docs.djangoproject.com/en/dev/ref/contrib/admin/#adminsite-attributes
admin.site.site_header = 'CCF administration'
admin.site.site_title = 'CCF site admin'


if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [
        path('__debug__/', include(debug_toolbar.urls)),
    ]

staff/urls.py
from django.urls import include
from django.urls import path

from . import views

app_name = 'staff'


application_patterns = [
    path('', views.ApplicationListView.as_view(), name='ccf-application-list'),
    path('reporting/application', views.DownloadApplicationsView.as_view(), name='ccf-application-download'),
    path('<uuid:pk>/', views.ApplicationDetailView.as_view(),
         name='application-detail'),
    path('<uuid:pk>/update', views.ApplicationUpdateView.as_view(),
         name='application-update'),
]

payments_patterns = [
    path('', views.PaymentsView.as_view(), name='payments'),
    #  path('mark_as_paid/', views.MarkAsPaidView.as_view(),
    #       name='mark-as-paid'),
    path('archive/', views.PaymentsArchiveView.as_view(), name='payments-archive'),
    path('auto_process_applications/',
         views.AutoProcessApplicationsView.as_view(), name='auto-process-applications'),
    path('<str:status>/', views.DownloadReportView.as_view(), name='download-report'),
]

voucher_patterns = [
    path('', views.VoucherCodeGenerateView.as_view(), name='voucher-gen'),
    path('csv/<str:batch_id>/',
         views.DownloadVoucherCodeBatchView.as_view(), name='download-voucher'),
    path('invalidate/<str:batch_id>/', views.VoucherCodeBatchInvalidateView.as_view(),
         name='voucher-batch-invalidate'),
    path('list/', views.VoucherCodeListView.as_view(), name='voucher-list'),
    path('list/create/<str:code>',
         views.VoucherCodeListCreateApplicationRedirectView.as_view(), name='create-app-redirect'),
    path('list/invalidate/', views.VoucherCodeListInvalidateView.as_view(),
         name='voucher-list-invalidate'),
    path('list/download/', views.VoucherCodeListDownloadView.as_view(),
         name='voucher-list-download'),
]

address_patterns = [
    path('', views.PreapprovedAddressGenerateView.as_view(),
         name='address-whitelist'),
]

admin_auth_override_patterns = [
    path('password_change/', views.LoginRequiredAfterPasswordChange.as_view()),
]

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('accounts/', include(admin_auth_override_patterns)),
    path('address/', include(address_patterns)),
    path('applications/', include(application_patterns)),
    path('logout/', views.staff_logout_view, name='logout'),
    path('payments/', include(payments_patterns)),
    path('voucher/', include(voucher_patterns)),
]

app_ccf/models.py
"""
Main tables in the application
"""
import uuid
from datetime import datetime
from datetime import timezone

from django.conf import settings
from django.contrib.postgres.fields import ArrayField
from django.core.validators import MinValueValidator
from django.db import models
from django.db import transaction
from django.utils.translation import ugettext_lazy as _

from shared.common import TypeOfWork
from shared.validation import clean_number_only_validator
from shared.validation import clean_phone_number_validator
from shared.validation import clean_voucher_validator_v1
from shared.validation import clean_zip_code_validator
from shared.validation import email_validator
from shared.validation import street_address_validator
from shared.validation import text_characters_only_validator

#  from django.core.files.storage import FileSystemStorage
# Any user-facing text should be preppended with _ to enable localization


def get_datetime_now_utc():
    """
    get the current time in UTC
    """
    return datetime.now(timezone.utc)


class VoucherCodeCheckStatus(models.IntegerChoices):
    """
    Possible states valoucher codes can have.
    """
    SUCCESS = 0
    CODE_NOT_FOUND = 1
    CODE_ALREADY_USED = 2
    CODE_EXPIRED = 3
    CODE_INVALIDATED = 4


class Application(models.Model):
    """
    Core data for applicant tracking
    """
    class AgeRange(models.TextChoices):
        """
        Possible age ranges of an applicant
        """
        RANGE__17 = '17', _('17_or_younger')
        RANGE__18_29 = '18-29', _('18-29')
        RANGE_30_49 = '30-49', _('30-49')
        RANGE_50_69 = '50-69', _('50-69')
        RANGE_70_PLUS = '70+', _('70_or_older')

    class HouseHoldIncome(models.TextChoices):
        """
        Possible income ranges of an applicant
        """
        UNDER_20K = '<20k', _('under_20k')
        BETWEEN_20K_40K = '20,000-39,999', _('between_20k_39k')
        BETWEEN_40K_60K = '40,000-59,999', _('between_40k_59k')
        BETWEEN_60K_80K = '60,000-79,999', _('between_60k_79k')
        ABOVE_80K = '80,000+', _('above_80k')

    class Language(models.TextChoices):
        """
        Preferred applicant language
        """
        ES = 'es', _('spanish')
        EN = 'en', _('english')

    # NOTE: may need to be translated
    class ApplicationStatus(models.TextChoices):
        """
        Status of an application payment, review, etc.
        """
        SUBMITTED = 'submitted'
        APPROVED = 'approved'
        NEEDS_REVIEW = 'needs_review'
        REJECTED = 'rejected'
        SENT_FOR_PAYMENT = 'sent_for_payment'
        PAYMENT_CONFIRMED = 'payment_confirmed'
        REISSUE_REQUESTED = 'reissue_requested'
        REISSUE_CONFIRMED = 'reissue_confirmed'

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.set_last_status(self.status)

    def last_status(self):
        """
        get the last_status property if it was set
        """
        if self._last_status:
            return self._last_status
        raise ValueError("Last status was not recorded")

    def set_last_status(self, next_status):
        """
        sets _last_status using next_status
        """
        self._last_status = next_status

    @classmethod
    @transaction.atomic
    def bulk_update_status(cls, applications, new_status):
        """Bulk updates the status of a list of Applications."""
        datetime_now_utc = datetime.now(timezone.utc)
        status_updates = []

        for app in applications:
            if app.submitted_date is None:
                raise ValueError('Cannot update statuses for an unsubmitted application:', app.application_id)

            # We need to duplicate the save() logic a little bit here because
            # bulk_update doesn't call save().
            if app.last_status() != new_status:
                app.status = new_status
                app.status_last_modified = datetime_now_utc
                status_updates.append(
                    StatusUpdate(status=new_status, application=app)
                )

        cls.objects.bulk_update(applications, ['status', 'status_last_modified'], batch_size=30)
        StatusUpdate.objects.bulk_create(status_updates, batch_size=30)

        for app in applications:
            app.set_last_status(new_status)

    @transaction.atomic
    def save(self, *args, **kwargs):
        """
        Save a single application status update
        """
        datetime_now_utc = datetime.now(timezone.utc)
        if self.submitted_date is None:
            self.submitted_date = datetime_now_utc
        if self._state.adding or self.status != self._last_status:
            self.set_last_status(self.status)
            self.status_last_modified = datetime_now_utc
            StatusUpdate(status=self.status, application=self).save()
        self.full_clean()
        super().save(*args, **kwargs)

    def get_full_address(self):
        """
        Format a full address from parts
        """
        if self.addr2:
            addr_lines = '\n'.join([self.addr1, self.addr2])
        else:
            addr_lines = self.addr1
        city_line = '%s, %s %s' % (self.city, self.state, self.zip_code)
        return '\n'.join([addr_lines, city_line])

    type_of_work = models.CharField(
        max_length=15,
        choices=TypeOfWork.choices,
        default=TypeOfWork.HOUSE_CLEANING,
        blank=True,
    )
    vouchercode_str = models.CharField(max_length=settings.VOUCHER_CODE_MAX_LENGTH, validators=[clean_voucher_validator_v1()], db_index=True)
    first_name = models.CharField(max_length=200, blank=False, validators=[text_characters_only_validator()], db_index=True)
    last_name = models.CharField(max_length=200, blank=False, validators=[text_characters_only_validator()], db_index=True)
    payment_confirmed_reminder_sent = models.BooleanField(default=False)
    age_range = models.CharField(
        max_length=6,
        choices=AgeRange.choices,
        default=AgeRange.RANGE__17,
    )
    household_size = models.SmallIntegerField(
        validators=[MinValueValidator(1)],
        null=True,
        blank=True
    )
    household_income = models.CharField(
        max_length=20,
        choices=HouseHoldIncome.choices,
        default=HouseHoldIncome.UNDER_20K,
    )
    ethnicity = ArrayField(
        models.CharField(max_length=50, blank=True),
        size=8,
        default=list,
        blank=True,
    )
    gender = ArrayField(
        models.CharField(max_length=50, blank=True),
        size=8,
        default=list,
        blank=True,
    )
    language = models.CharField(
        max_length=15,
        choices=Language.choices,
        default=Language.EN,
    )
    # Regex matches a US phone number without ext or country code
    phone_number = models.CharField(max_length=10, validators=[clean_phone_number_validator()], db_index=True)
    email = models.EmailField(blank=True, validators=[email_validator()], db_index=True)
    addr1 = models.CharField(max_length=200, validators=[street_address_validator()], db_index=True)
    addr2 = models.CharField(max_length=100, blank=True, validators=[street_address_validator()], db_index=True)
    city = models.CharField(max_length=100, validators=[street_address_validator()], db_index=True)
    state = models.CharField(max_length=100, db_index=True)
    zip_code = models.CharField(max_length=9, validators=[clean_zip_code_validator()])
    # True if the user provided a verified USPS address.
    usps_verified = models.BooleanField(default=False)
    # True if the user selected a standardized version of the address.
    usps_standardized = models.BooleanField(default=False)
    signature = models.CharField(max_length=200)

    application_id = models.UUIDField(primary_key=True, default=uuid.uuid4, db_index=True)
    submitted_date = models.DateTimeField()
    status = models.CharField(
        max_length=40,
        choices=ApplicationStatus.choices,
        default=ApplicationStatus.SUBMITTED,
        db_index=True
    )
    status_last_modified = models.DateTimeField(null=True)
    note = models.CharField(max_length=2000, blank=True)


class StatusUpdate(models.Model):
    """
    table tracks updates in payment status
    """
    application = models.ForeignKey(Application, on_delete=models.CASCADE)
    status = models.CharField(
        max_length=40,
        choices=Application.ApplicationStatus.choices,
        default=Application.ApplicationStatus.SUBMITTED,
    )
    update_dt = models.DateTimeField(auto_now_add=True)


class DistributorXRef(models.Model):
    """Cross reference table for Distributors (CBOs) used for code generation and payment submission"""
    distributor_id = models.CharField(primary_key=True, max_length=10, validators=[clean_number_only_validator()])
    name = models.CharField(max_length=100)
    manager = models.CharField(max_length=100, blank=True, null=True)


class VoucherCodeBatch(models.Model):
    """
    Captures a batch of generated codes created together with common properties.

    Stores common fields among codes that were previously stored on the codes
    themselves.

    Fields:
      created: The date the batch was created, automatically set upon creation.
      user: The username of the staff portal user who created the batch.
      num_codes: The number of codes in the batch.
      code_length: The length of each code in the batch.
      alphabet: The set of characters the codes are created from.
      base_amount: The base dollar amount set for the batch.
      expiration_date: The date the codes are set to expire.
      affiliate: A text label indicating the affiliate the batch is associated
        with.
      campaign: A text label indicating the campaign the batch is associated
        with.
      channel: A text label indicating the channel the batch is associated
        with.
    """
    created = models.DateTimeField()
    admin_user = models.CharField(max_length=20)

staff/models.py
# -*- coding: utf-8 -*-
"""
    cash-assistance-platform.models
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

    Staff Page Data models
"""
#  from datetime import datetime
#  from datetime import timezone
#  from django.contrib.postgres.fields import JSONField
from django.db import models
from django.db.models import JSONField

from app_ccf.encoder import ApplicationEncoder
from app_ccf.models import Application


class AdminAction(models.Model):
    """
    Represents and action taken by an administrator on an Application.

    Captures the application details before and after the change.
    """
    class AdminActionType(models.TextChoices):
        """
        Represents the types of actions an admin can take to manipulate
        an application.
        """
        MANUAL_EDIT = 'manual_edit'
        AUTOMATED_FLAG = 'automated_flag'
        LAMBDA = 'lambda'

    application = models.ForeignKey(Application, on_delete=models.CASCADE)
    admin_user = models.CharField(max_length=20)
    action_dt = models.DateTimeField(auto_now_add=True)
    action_type = models.CharField(max_length=40,
                                   choices=AdminActionType.choices)
    #  text1 = models.CharField(max_length=320, default="")
    initial_app_json = JSONField(encoder=ApplicationEncoder)
    final_app_json = JSONField(encoder=ApplicationEncoder)

    @property
    def initial_app(self):
        """The Application before the action."""
        return Application(**self.initial_app_json)

    @property
    def final_app(self):
        """The Application after the action."""
        return Application(**self.final_app_json)

    @property
    def changed_fields(self):
        """The model fields that changed during the transaction.

        Returns:
            A list of 3-tuples of:
                - The field name
                - The initial value
                - The final value
        """
        changes = []
        for field in self.initial_app_json:
            initial_value = getattr(self.initial_app, field)
            final_value = getattr(self.final_app, field)
            if initial_value != final_value:
                changes.append((field, initial_value, final_value))
        return changes

staff/templates/staff/applications/application_details.html
{% extends "base_staff.html" %}
{% load static i18n %}
{% load widget_tweaks %}
{% block title %}CEAP | Staff | Application {% endblock %}
{% block sidebar-ccf-application-items %} {{block.super}}
{% endblock sidebar-ccf-application-items %}

{% block main %}
<nav aria-label="breadcrumb" class="h5 pt-3 pb-3">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><a
        href="{% url 'staff:ccf-application-list' %}">Applications</a>
    </li>
    <li class="breadcrumb-item active" aria-current="page">
      [{{ application.last_name }}, {{ application.first_name }}]</li>
  </ol>
</nav>
<div class="card mb-5 shadow-sm">
  <div class="card-header px-3 bg-white">
    <div class="row justify-content-between">
      <div class="col-4">
        <h5>Profile</h5>
      </div>
      <div class="col-4 text-right">
        <a class="btn btn-light btn-sm border shadow-sm"
           href="{% url 'staff:application-update' application.application_id %}">
          <i class="material-icons md-18">edit</i>Edit</a>
      </div>
    </div>
  </div>
  <div class="card-body">
    <div class="row">
      <div class="col-sm">
        <p>APPLICATION INFORMATION</p>
        <div class="table-responsive">
          <table class="table table-sm table-borderless m-0" onload="getDates()">
            <tr>
              <td class="text-secondary">Name (last, first)</td>
              <td>{{ application.last_name }},
                {{ application.first_name }}</td>
            </tr>
            <tr>
              <td class="text-secondary">Voucher Code</td>
              <td>{{ application.vouchercode_str }}</a></td>
            </tr>
            <tr>
              <td class="text-secondary">Channel</td>
              <td>{{ code.channel }}</td>
            </tr>
            <tr>
              <td class="text-secondary">Affiliate</td>
              <td>{{ code.affiliate.name }}</td>
            </tr>
            <tr>
              <td class="text-secondary">Campaign</td>
              <td>{{ code.campaign }}</td>
            </tr>
            <tr>
              <td class="text-secondary">Submit date</td>
              <td id="submitted_dt">{{ application.submitted_date|date:"c" }}</td>
            </tr>
            <tr>
              <td class="text-secondary">Preferred language</td>
              <td>{{ application.get_language_display }}</td>
            </tr>
            <tr>
              <td class="text-secondary">Status</td>
              <td>{{ application.get_status_display }}</td>
            </tr>
            <tr>
              <td class="text-secondary">Status Last Modified</td>
              <td id="modified_dt">{{ application.status_last_modified|date:"c" }}</td>
            </tr>
            <tr>
              <td class="text-secondary">Note</td>
              <td>{{ application.note|linebreaksbr }}</td>
            </tr>
          </table>
        </div>
      </div>
      <div class="col-sm">
        <p>CONTACT INFORMATION</p>
        <div class="table-responsive">
          <table class="table table-sm table-borderless">
            <tr>
              <td class="text-secondary">Email</td>
              <td>{{ application.email }}</td>
            </tr>
            <tr>
              <td class="text-secondary">Phone</td>
              <td>{{ application.phone_number }}</td>
            </tr>
            <tr>
              <td class="text-secondary">Street</td>
              <td>{{ application.addr1 }}</td>
            </tr>
            <tr>
              <td class="text-secondary">Street (contd.)</td>
              <td>{{ application.addr2 }}</td>
            </tr>
            <tr>
              <td class="text-secondary">City</td>
              <td>{{ application.city }}</td>
            </tr>
            <tr>
              <td class="text-secondary">State</td>
              <td>{{ application.state }}</td>
            </tr>
            <tr>
              <td class="text-secondary">Zip</td>
              <td>{{ application.zip_code }}</td>
            </tr>
            <tr>
              <td class="text-secondary">USPS Standardized</td>
              <td>{{ application.usps_standardized }}</td>
            </tr>
            <tr>
              <td class="text-secondary">USPS Verified</td>
              <td>{{ application.usps_verified }}</td>
            </tr>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>
{% if application.statusupdate_set.all %}
<div class="card mb-5 shadow-sm" style="width:400px;">
  <div class="card-header px-3 bg-white">
    <h5>Status Updates</h5>
  </div>
  <div>
    <table class="table">
      <thead>
        <tr>
          <th scope="col">Date</th>
          <th scope="col">Status</th>
        </tr>
      </thead>
      <tbody>
        {% for update in application.statusupdate_set.all %}
        <tr>
					<td id="update_dt" />{{ update.update_dt|date:"c" }}</td>
          <td>{{ update.get_status_display }}</td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
</div>
{% endif %}
{% if application.adminaction_set.all %}
<div class="card mb-5 shadow-sm" style="width:800px">
  <div class="card-header px-3 bg-white">
    <h5>Admin Actions</h5>
  </div>
  <div>
    <table class="table">
      <thead>
        <tr>
          <th scope="col">Date</th>
          <th scope="col">Action Type</th>
          <th scope="col">User</th>
          <th scope="col">Changed Fields</th>
        </tr>
      </thead>
      <tbody>
        {% for action in application.adminaction_set.all %}
        <tr>
					<td id="action_dt" />{{ action.action_dt|date:"c" }}</td>
          <td>{{ action.get_action_type_display }}</td>
          <td>{{ action.admin_user }}</td>
          <td>
            <table class="table-sm">
              <tbody>
                {% for field in action.changed_fields %}
                <tr>
                  <td>{{field.0}}:</td>
                  <td>
                    {% if field.1 %}
                    <span><strike>{{ field.1 }}</strike></span><br />
                    {% endif %}
                    <span
                      class="text-success">{{ field.2 }}</span>
                  </td>
                </tr>
                {% endfor %}
              </tbody>
            </table>
          </td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
</div>
{% endif %}
<script>
	window.onload = function() { $("td[id*='dt']").each(function() { $(this).text(formatDay($(this).text())) }); }
	function formatDay(dateString) { return dayjs(dateString).format('MMM DD, YYYY h:mm A') }
</script>
{% endblock main %}

staff/templates/staff/applications/application_list.html
{% extends "base_staff.html" %}
{% load static i18n %}
{% load widget_tweaks %}

{% block main %}

<div class="p-4 container-fluid">
  <p class="h3">{% blocktrans %}Applications{% endblocktrans %}</p>
  <div class="" role="toolbar">
    <div class="">
      <form class="border p-3" style="width: 900px;" action="" method="get" class="form">
        <div class="row">
          <div class="form-group col-sm-4 col-md-3">
            {{ filter.form.status.label_tag }}
            {% render_field filter.form.status class="form-control" %}
          </div>
          <div class="form-group col-sm-4 col-md-3">
            {{ filter.form.vouchercode_str__icontains.label_tag }}
            {% render_field filter.form.vouchercode_str__icontains class="form-control" %}
          </div>
          <div class="form-group col-sm-4 col-md-3">
            {{ filter.form.email__icontains.label_tag }}
            {% render_field filter.form.email__icontains class="form-control" %}
          </div>
        </div>
        <div class="row">
          <div class="form-group col-sm-4 col-md-3">
            {{ filter.form.first_name__unaccent__icontains.label_tag }}
            {% render_field filter.form.first_name__unaccent__icontains class="form-control" %}
          </div>
          <div class="form-group col-sm-4 col-md-3">
            {{ filter.form.last_name__unaccent__icontains.label_tag }}
            {% render_field filter.form.last_name__unaccent__icontains class="form-control" %}
          </div>
          <div class="form-group col-sm-4 col-md-3">
            {{ filter.form.phone_number__icontains.label_tag }}
            {% render_field filter.form.phone_number__icontains class="form-control" %}
          </div>
        </div>
        <div class="row">
          <div class="form-group col-sm-4 col-md-3">
            {{ filter.form.addr1__icontains.label_tag }}
            {% render_field filter.form.addr1__icontains class="form-control" %}
          </div>
          <div class="form-group col-sm-4 col-md-3">
            {{ filter.form.addr2__icontains.label_tag }}
            {% render_field filter.form.addr2__icontains class="form-control" %}
          </div>
          <div class="form-group col-sm-4 col-md-3">
            {{ filter.form.city__iexact.label_tag }}
            {% render_field filter.form.city__iexact class="form-control" %}
          </div>
          <div class="form-group col-sm-4 col-md-3">
            {{ filter.form.state__iexact.label_tag }}
            {% render_field filter.form.state__iexact class="form-control" %}
          </div>
        </div>
        <button class="btn btn-primary btn-sm btn-icon" role="submit">
          <i class="material-icons md-18">search</i>{% translate 'Search' %}
        </button>
      </form>
    </div>
    <div class="p-4">
  		<span style="padding-right: 50px">
      Showing <b>{{ application_list | length }}</b> of <b>{{ filter.qs | length }}</b> applications.
      </span>
  			<a href="{% url 'staff:ccf-application-download' %}">
      		<button class="btn btn-primary btn-sm btn-icon">
      			<i class="material-icons md-18">file_download</i>{% translate 'Export All Applications' %}
      		</button>
  			</a>
    </div>
  </div>
  <div>
    <table class="table table-hover">
      <thead>
        <tr>
          <th scope="col">{% translate 'Name' %}</th>
          <th scope="col">{% translate 'Affiliate ID' %}</th>
          <th scope="col">{% translate 'Affiliate' %}</th>
          <th scope="col">{% translate 'Submit Date' %}</th>
          <th scope="col">{% translate 'Last Updated' %}</th>
          <th scope="col">{% translate 'Status' %}</th>
          <th scope="col">{% translate 'Note' %}</th>
          <th scope="col">{% translate 'Code' %}</th>
          <th scope="col">{% translate 'Phone' %}</th>
          <th scope="col">{% translate 'Address' %}</th>
        </tr>
      </thead>
      <tbody>
      	{% for app in application_list %}
        <tr>
          <td><a href="{% url 'staff:application-detail' app.application_id %}">{{ app.last_name }}, {{ app.first_name }}</a></td>
          <td>{{ app.vouchercode.affiliate.distributor_id }}</td>
          <td>{{ app.vouchercode.affiliate.name }}</td>
          <td id="submitted_dt">{{ app.submitted_date|date:"c" }}</td>
          <td id="submitted_dt">{{ app.status_last_modified|date:"c" }}</td>
          <td>{{ app.get_status_display }}</td>
          <td>{{ app.note|linebreaksbr|truncatechars:400 }}</td>
          <td>{{ app.vouchercode_str }}</td>
          <td>{{ app.phone_number }}</td>
          <td>{{ app.get_full_address }}</td>
        </tr>
      	{% endfor %}
      </tbody>
    </table>
  	{% include 'staff/snippets/pagination.html' with object_list=application_list%}
  </div>
</div>
<script>
	window.onload = function() { $("td[id*='dt']").each(function() { $(this).text(formatDay($(this).text())) }); }
	function formatDay(dateString) { return dayjs(dateString).format('MMM DD, YYYY h:mm A') }
</script>
{% endblock main %}

staff/templates/staff/applications/payment_action_archive.html
{% extends "base_staff.html" %}
{% block title %}CEAP | Staff | Voucher codes {% endblock %}
{% block sidebar-ccf-application-items %} {{block.super}}
{% endblock sidebar-ccf-application-items %}


{% block main %}

<div class="p-4 container-fluid">
  <p class="h3">History</p>
  <div>
    <table class="table table-hover mt-4">
      <thead>
        <tr>
          <th scope="col">Download</th>
          <th scope="col">Name</th>
          <th scope="col">Date</th>
        </tr>
      </thead>
      <tbody>
				{% for file in object_list %}
				<tr>
					<td>
						<a href="{{ file.Link }}" download>
							<i class="material-icons" style="vertical-align: middle">file_download</i>
							Download
						</a>
					</td>
					<td>{{ file.Name }}</td>
					<td id="archived_dt">{{ file.Date|date:"c" }}</td>
				</tr>
				{% endfor %}
      </tbody>
    </table>
  </div>
</div>

<script>
	window.onload = function() { $("td[id*='dt']").each(function() { $(this).text(formatDay($(this).text())) }); }
		function formatDay(dateString) { return dayjs(dateString).format('MMM DD, YYYY h:mm A') }
</script>
{% endblock %}