ccf/urls.py
from django.conf import settings
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin
from django.urls import include
from django.urls import path
from django.urls import re_path
from two_factor.admin import AdminSiteOTPRequired
from two_factor.urls import urlpatterns as tf_urls

import app_ccf
from app_ccf.views import DASTStagingView
from app_ccf.views import LanguageView
#  from django.views.generic import RedirectView

handler400 = app_ccf.views.UnknownErrorView.get_rendered_view(status_code=400)
handler403 = app_ccf.views.UnknownErrorView.get_rendered_view(status_code=403)
handler404 = app_ccf.views.UnknownErrorView.get_rendered_view(status_code=404)
handler500 = app_ccf.views.ServerErrorView.get_rendered_view(status_code=500)

admin.site.__class__ = AdminSiteOTPRequired

ccfpatterns = [
    re_path(
        r'^(?P<accesscode>([a-zA-Z]{3}-[a-zA-Z]{3}-[a-zA-Z]{3}))/$',
        LanguageView.as_view(),
        name='language'
    ),
    path('', LanguageView.as_view(), name='language'),
    path('language', LanguageView.as_view(), name='language'),
    path('GitLab-DAST-Site-Validation-17640645-2256-4bca-a59f-982e79787585.txt', DASTStagingView.as_view(), name='staging-dast')
]

ccfpatterns += i18n_patterns(
    path('', include('app_ccf.urls')),
)

staffpatterns = [
    path('', include('staff.urls')),
    path('ssa/', admin.site.urls),
    path('accounts/', include('admin_honeypot.urls')),
    path('mfa/', include(tf_urls)),
]

urlpatterns = [
    path('i18n/', include('django.conf.urls.i18n')),
    path('session_security/', include('session_security.urls')),
]
# Based on app type variable, set urlpatterns
if settings.APP_TYPE == 'CCF':
    urlpatterns += ccfpatterns
elif settings.APP_TYPE == 'STAFF':
    urlpatterns += staffpatterns
else:  # Local/demo have access to staff urls directly from '/staff/'
    urlpatterns += ccfpatterns
    urlpatterns += [
        path('staff/', include(staffpatterns))
    ]

# https://docs.djangoproject.com/en/dev/ref/contrib/admin/#adminsite-attributes
admin.site.site_header = 'CCF administration'
admin.site.site_title = 'CCF site admin'


if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [
        path('__debug__/', include(debug_toolbar.urls)),
    ]

staff/urls.py
from django.urls import include
from django.urls import path

from . import views

app_name = 'staff'


application_patterns = [
    path('', views.ApplicationListView.as_view(), name='ccf-application-list'),
    path('reporting/application', views.DownloadApplicationsView.as_view(), name='ccf-application-download'),
    path('<uuid:pk>/', views.ApplicationDetailView.as_view(),
         name='application-detail'),
    path('<uuid:pk>/update', views.ApplicationUpdateView.as_view(),
         name='application-update'),
]

payments_patterns = [
    path('', views.PaymentsView.as_view(), name='payments'),
    #  path('mark_as_paid/', views.MarkAsPaidView.as_view(),
    #       name='mark-as-paid'),
    path('archive/', views.PaymentsArchiveView.as_view(), name='payments-archive'),
    path('auto_process_applications/',
         views.AutoProcessApplicationsView.as_view(), name='auto-process-applications'),
    path('<str:status>/', views.DownloadReportView.as_view(), name='download-report'),
]

voucher_patterns = [
    path('', views.VoucherCodeGenerateView.as_view(), name='voucher-gen'),
    path('csv/<str:batch_id>/',
         views.DownloadVoucherCodeBatchView.as_view(), name='download-voucher'),
    path('invalidate/<str:batch_id>/', views.VoucherCodeBatchInvalidateView.as_view(),
         name='voucher-batch-invalidate'),
    path('list/', views.VoucherCodeListView.as_view(), name='voucher-list'),
    path('list/create/<str:code>',
         views.VoucherCodeListCreateApplicationRedirectView.as_view(), name='create-app-redirect'),
    path('list/invalidate/', views.VoucherCodeListInvalidateView.as_view(),
         name='voucher-list-invalidate'),
    path('list/download/', views.VoucherCodeListDownloadView.as_view(),
         name='voucher-list-download'),
]

address_patterns = [
    path('', views.PreapprovedAddressGenerateView.as_view(),
         name='address-whitelist'),
]

admin_auth_override_patterns = [
    path('password_change/', views.LoginRequiredAfterPasswordChange.as_view()),
]

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('accounts/', include(admin_auth_override_patterns)),
    path('address/', include(address_patterns)),
    path('applications/', include(application_patterns)),
    path('logout/', views.staff_logout_view, name='logout'),
    path('payments/', include(payments_patterns)),
    path('voucher/', include(voucher_patterns)),
]

staff/models.py
# -*- coding: utf-8 -*-
"""
    cash-assistance-platform.models
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

    Staff Page Data models
"""
#  from datetime import datetime
#  from datetime import timezone
#  from django.contrib.postgres.fields import JSONField
from django.db import models
from django.db.models import JSONField

from app_ccf.encoder import ApplicationEncoder
from app_ccf.models import Application


class AdminAction(models.Model):
    """
    Represents and action taken by an administrator on an Application.

    Captures the application details before and after the change.
    """
    class AdminActionType(models.TextChoices):
        """
        Represents the types of actions an admin can take to manipulate
        an application.
        """
        MANUAL_EDIT = 'manual_edit'
        AUTOMATED_FLAG = 'automated_flag'
        LAMBDA = 'lambda'

    application = models.ForeignKey(Application, on_delete=models.CASCADE)
    admin_user = models.CharField(max_length=20)
    action_dt = models.DateTimeField(auto_now_add=True)
    action_type = models.CharField(max_length=40,
                                   choices=AdminActionType.choices)
    #  text1 = models.CharField(max_length=320, default="")
    initial_app_json = JSONField(encoder=ApplicationEncoder)
    final_app_json = JSONField(encoder=ApplicationEncoder)

    @property
    def initial_app(self):
        """The Application before the action."""
        return Application(**self.initial_app_json)

    @property
    def final_app(self):
        """The Application after the action."""
        return Application(**self.final_app_json)

    @property
    def changed_fields(self):
        """The model fields that changed during the transaction.

        Returns:
            A list of 3-tuples of:
                - The field name
                - The initial value
                - The final value
        """
        changes = []
        for field in self.initial_app_json:
            initial_value = getattr(self.initial_app, field)
            final_value = getattr(self.final_app, field)
            if initial_value != final_value:
                changes.append((field, initial_value, final_value))
        return changes

staff/views.py
# -*- coding: utf-8 -*-
"""
    cash-assistance-platform.staff.views
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

    Staff applications views

    :copyright: (c) 2021 by YOUR_NAME.
    :license: LICENSE_NAME, see LICENSE for more details.
"""
import csv
import io
import logging
import os
import pprint
import urllib.parse
from collections import OrderedDict
from datetime import datetime
from datetime import timedelta
from datetime import timezone

from django.utils.translation import ugettext_lazy as _
import unidecode
from backoff import expo
from backoff import on_exception
from django.conf import settings
from django.contrib import messages
from django.contrib.auth import logout
from django.contrib.auth.views import PasswordChangeView
from django.db import transaction
from django.db.models import Q
from django.db.models.functions import Lower
from django.forms import Textarea
from django.forms.models import model_to_dict
from django.forms.models import modelform_factory
from django.http import FileResponse
from django.http import HttpResponse
from django.http import HttpResponseRedirect
from django.shortcuts import redirect
from django.shortcuts import render
from django.template.defaultfilters import slugify
from django.urls import reverse
from django.views.generic import DetailView
from django.views.generic import ListView
from django.views.generic import TemplateView
from django.views.generic import UpdateView
from django.views.generic import View
from django.views.generic.base import ContextMixin
from django.views.generic.edit import CreateView
from django_filters import ChoiceFilter
from django_filters import FilterSet
from django_filters import ModelChoiceFilter
from django_filters import rest_framework as rest_filters
from django_filters.views import FilterView
from django_tables2 import MultiTableMixin
from ratelimit import limits
from ratelimit import RateLimitException
from rest_framework import generics
from rest_framework.views import APIView

from .forms import ApprovedApplicationTable
from .forms import PreapprovedAddressGenerateForm
from .forms import VoucherCodeGenerateForm
from .mixins import StaffRequiredMixin
from .mixins import SuperUserRequiredMixin
from .models import AdminAction
from .utils import generate_voucher_codes
from .utils import get_archived_payment_actions
from .utils import import_voucher_codes
from .utils import invalidate_voucher_codes_with_code_list
from .utils import upload_payment_action_archive
from app_ccf import common
from app_ccf import notification
from app_ccf.config import get_config
from app_ccf.models import Application
from app_ccf.models import DistributorXRef
from app_ccf.models import PreapprovedAddress
from app_ccf.models import VoucherCode
from app_ccf.models import VoucherCodeBatch
#  from .utils import deregister_card
#  from .utils import load_card
#  from .utils import send_applicant_info
#  from .utils import send_card_info
#  from app_ccf import text_messages
#  from django_tables2 import SingleTableView
#  from django.contrib.auth.mixins import LoginRequiredMixin
#  from django.contrib.auth.models import User
#  from django.core.files import File
#  from django.shortcuts import get_object_or_404
#  from django.template.loader import render_to_string
#  from django.urls import reverse_lazy
#  from django_filters import CharFilter, DateFromToRangeFilter
#  from django_filters.widgets import RangeWidget
#  from .utils import invalidate_voucher_codes_with_campaign

PPRINTER = pprint.PrettyPrinter(indent=2)
LOGGER = logging.getLogger(__name__)


def ccf_bad_request_view(request):
    """
    shown on bad http request
    """
    messages.error(request, 'Bad request.')
    return render(
        request,
        'staff/40x.html',
        status=400
    )


def ccf_permssion_denied_view(request):
    """
    shown when you lack permission for a page
    """
    messages.error(request, 'You are not allowed to view this page.')
    return render(
        request,
        'staff/40x.html',
        status=403
    )


def ccf_not_found_view(request):
    """
    shown when a page does not exist
    """
    messages.error(request, 'Page not found.')
    return render(
        request,
        'staff/40x.html',
        status=404
    )


def staff_logout_view(request):
    """
    shown on logout
    """
    logout(request)
    messages.info(request, 'Logged out successfully')
    return redirect('staff:index')


# # # # # # # # # # # # # # # # # # # # # # # #
# Staff-required CCF application related views
# # # # # # # # # # # # # # # # # # # # # # # #

class ApplicationFilter(FilterSet):
    """Application filter used when loading Application table"""
    class Meta:
        """
        Meta
        """
        model = Application
        fields = {'status': ['exact'],
                  'first_name': ['unaccent__icontains'],
                  'last_name': ['unaccent__icontains'],
                  'phone_number': ['icontains'],
                  'vouchercode_str': ['icontains'],
                  'email': ['icontains'],
                  'addr1': ['icontains'],
                  'addr2': ['icontains'],
                  'city': ['iexact'],
                  'state': ['iexact'],
                  }


class IndexView(StaffRequiredMixin, TemplateView):
    """
    Base page
    """
    template_name = 'staff/index.html'


def index_view(
    #  request
):
    """
    This view is a FAKE login page that a potential hacker may use.
    """
    # TODO: Additional config needed for notifying admins of login attempts.
    # TODO: customization of login pages.
    return HttpResponseRedirect(reverse('admin_honeypot:login',))


class PaginatedFilterViewMixin(View):
    """
    TBD
    """

    def get_context_data(self, **kwargs):
        """
        context data for the html template
        """
        context = super().get_context_data(**kwargs)
        # Get filter params if in URL querystring
        if self.request.GET:
            querystring = self.request.GET.copy()
            if self.request.GET.get('page'):
                del querystring['page']
            context['params_GET'] = querystring.urlencode()
        return context


class AutoProcessApplicationsView(StaffRequiredMixin, TemplateView):
    """
    TBD
    """

    def post(self, request, *args, **kwargs):
        """
        initiate application update
        """
        common.auto_update_application_statuses()
        return HttpResponseRedirect(reverse('staff:payments'))


class ApplicationListView(StaffRequiredMixin, PaginatedFilterViewMixin, ListView):
    """
    Show applications in a table, filterable
    """
    model = Application
    template_name = "staff/applications/application_list.html"
    ordering = ["last_name", "first_name", "-submitted_date"]
    paginate_by = 10

    def get_queryset(self):
        """
        get entries
        """
        queryset = ApplicationFilter(
            self.request.GET,
            queryset=self.model.objects.all().order_by(*self.ordering)
        ).qs
        return queryset

    def get_context_data(self, **kwargs):
        """
        context data for use in the html template
        """
        context = super().get_context_data(**kwargs)
        context['filter'] = ApplicationFilter(
            self.request.GET, queryset=self.get_queryset())
        return context


class ApplicationDetailView(StaffRequiredMixin, DetailView):
    """
    show application information for a single person in detail with changetsets
    """
    model = Application
    template_name = "staff/applications/application_details.html"

    def get_context_data(self, **kwargs):
        """
        context data for the html template
        """
        context = super().get_context_data(**kwargs)
        context['code'] = self.object.vouchercode
        return context


class LoginRequiredAfterPasswordChange(PasswordChangeView):
    """
    TBD
    """
    @property
    def success_url(self):
        """
        TBD
        """
        messages.success(
            self.request,
            'You have successfully updated you password.'
        )
        return reverse('staff:index')


# # # # # # # # # # # # # # # # # # # # # # # #
# Superuser-required views
# # # # # # # # # # # # # # # # # # # # # # # #


class SuperUserAccessedView(SuperUserRequiredMixin, TemplateView):
    """
    TBD
    """
    template_name = None


class ApplicationUpdateView(StaffRequiredMixin, UpdateView):
    """
    page contains a form that allows edits to an individual applicant
    """
    model = Application
    template_name = "staff/applications/application_update.html"
    form_class = modelform_factory(
        Application,
        fields=['first_name', 'last_name', 'phone_number', 'email', 'addr1',
                'addr2', 'city', 'state', 'zip_code', 'status', 'note'],
        widgets={'note': Textarea(attrs={'cols': 30,
                                         'rows': 3,
                                         'style': 'vertical-align: top'})})

    def get_form(self, *args, **kwargs):
        form = super(ApplicationUpdateView, self).get_form(*args, **kwargs)
        form.fields['note'].required = True
        return form

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context

    def get_success_url(self):
        return reverse('staff:application-detail', kwargs={'pk': self.object.pk})

    @on_exception(expo, RateLimitException, max_tries=2)
    @limits(calls=5, period=1)
    @transaction.atomic
    def form_valid(self, form):
        if form.has_changed():
            initial = model_to_dict(self.get_object())
            final = model_to_dict(self.object)
            admin_action = AdminAction(
                admin_user=self.request.user.username,
                application=self.object,
                action_type=AdminAction.AdminActionType.MANUAL_EDIT,
                initial_app_json=initial,

staff/templates/base_staff.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    {% block head %}
    {{ block.super }}
    <title>{% block title %}CEAP Staff{% endblock %}</title>
    <link rel="stylesheet"
        href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css"
        integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS"
        crossorigin="anonymous">
    <script
    	src="https://cdn.jsdelivr.net/npm/dayjs@1.10.4/dayjs.min.js"
    	integrity="sha256-NTsR4SOm3YHfJrmrmvBtEYqfQ6jQ5yvEKMhgQe3DIl0="
    	crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.3.1.min.js"
        integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8="
        crossorigin="anonymous"></script>
    <script
        src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js"
        integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut"
        crossorigin="anonymous"></script>
    <script
        src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js"
        integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k"
        crossorigin="anonymous"></script>
    <script src="{% static 'staff/js/dashboard.js' %}"></script>
    <style>
        .bd-placeholder-img {
            font-size: 1.125rem;
            text-anchor: middle;
        }

        @media (min-width: 768px) {
            .bd-placeholder-img-lg {
                font-size: 3.5rem;
            }
        }
    </style>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons"
        rel="stylesheet">
    <link rel="stylesheet" href="{% static 'staff/css/dashboard.css' %}">
    {% endblock head %}
</head>

<body>
    <!-- Google Tag Manager (noscript) -->
    <nav class="navbar navbar-dark fixed-top flex-md-nowrap p-0 shadow">
        <a class="navbar-brand col-sm-3 col-md-2 mr-0"
            href="{% url 'staff:index' %}">
            {% block portal-identifier %}
            CEAP / Staff
            {% endblock portal-identifier %}
        </a>
    </nav>
    <div class="container-fluid">
        <div class="row">

            <nav class="col-md-2 d-none d-md-block sidebar">
                <div class="sidebar-sticky">
                    {% block body %}
                    <ul class="nav flex-column">
                        {% block sidebar-standalone-items %}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'staff:index' %}">
                                <i class="material-icons">dashboard</i>
                                Dashboard
                            </a>
                        </li>
                        {% endblock sidebar-standalone-items %}
                    </ul>
                    <h6
                        class="sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-muted">
                        <span>CEAP Applications</span>
                    </h6>
                    <ul class="nav flex-column">
                        {% block sidebar-ccf-application-items %}
                        <li class="nav-item">
                            <a class="nav-link"
                                href="{% url 'staff:ccf-application-list' %}">
                                <i class="material-icons">people</i>
                                All Applications
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link"
                                href="{% url 'staff:payments' %}">
                                <i class="material-icons">payment</i>
                                Payment Actions
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link"
                                href="{% url 'staff:payments-archive' %}">
                                <i class="material-icons">unarchive</i>
                                Payment Export Archive
                            </a>
                        </li>
                        {% endblock sidebar-ccf-application-items %}
                    </ul>
                    <h6
                        class="sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-muted">
                        <span>Voucher Codes</span>
                    </h6>
                    <ul class="nav flex-column">
                        {% block sidebar-voucher-items %}
                        <li class="nav-item">
                            <a class="nav-link"
                                href="{% url 'staff:voucher-gen' %}">
                                <i class="material-icons">insert_emoticon</i>
                                Generate
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link"
                                href="{% url 'staff:voucher-list' %}">
                                <i
                                    class="material-icons">format_list_bulleted</i>
                                Codes
                            </a>
                        </li>
                        {% endblock sidebar-voucher-items %}
                    </ul>
                    <h6
                        class="sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-muted">
                        <span>Addresses</span>
                    </h6>
                    <ul class="nav flex-column">
                        {% block sidebar-address-items %}
                        <li class="nav-item">
                            <a class="nav-link"
                                href="{% url 'staff:address-whitelist' %}">
                                <i class="material-icons">domain</i>
                                Preapproved Addresses
                            </a>
                        </li>
                        {% endblock sidebar-address-items %}
                    </ul>
                    <h6
                        class="sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-muted">
                        <span>Account</span>
                    </h6>
                    <ul class="nav flex-column">
                        <li class="nav-item">
                            {% if  user.is_superuser %}
                            <a class="nav-link"
                                href="{% url 'admin:auth_user_add' %}">
                                <i class="material-icons">face</i>
                                Create User
                            </a>
                            {% endif %}
                            <a class="nav-link"
                                href="{% url 'admin:password_change' %}">
                                <i class="material-icons">update</i>
                                Reset Password
                            </a>
                            <a class="nav-link"
                                href="{% url 'two_factor:profile' %}">
                                <i class="material-icons">security</i>
                                Account Security
                            </a>
                            <a class="nav-link" href="{% url 'staff:logout' %}">
                                <i class="material-icons">power_settings_new</i>
                                Sign out
                            </a>
                        </li>
                    </ul>
                    {% endblock body %}
                </div>
            </nav>
            <main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-4">
                {% include "staff/snippets/toast_messages.html" %}
                {% block main %}{% endblock %}
            </main>
        </div>
    </div>
    {% include 'session_security/all.html' %}
</body>

</html>