ccf/urls.py
from django.conf import settings
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin
from django.urls import include
from django.urls import path
from django.urls import re_path
from two_factor.admin import AdminSiteOTPRequired
from two_factor.urls import urlpatterns as tf_urls

import app_ccf
from app_ccf.views import DASTStagingView
from app_ccf.views import LanguageView
#  from django.views.generic import RedirectView

handler400 = app_ccf.views.UnknownErrorView.get_rendered_view(status_code=400)
handler403 = app_ccf.views.UnknownErrorView.get_rendered_view(status_code=403)
handler404 = app_ccf.views.UnknownErrorView.get_rendered_view(status_code=404)
handler500 = app_ccf.views.ServerErrorView.get_rendered_view(status_code=500)

admin.site.__class__ = AdminSiteOTPRequired

ccfpatterns = [
    re_path(
        r'^(?P<accesscode>([a-zA-Z]{3}-[a-zA-Z]{3}-[a-zA-Z]{3}))/$',
        LanguageView.as_view(),
        name='language'
    ),
    path('', LanguageView.as_view(), name='language'),
    path('language', LanguageView.as_view(), name='language'),
    path('GitLab-DAST-Site-Validation-17640645-2256-4bca-a59f-982e79787585.txt', DASTStagingView.as_view(), name='staging-dast')
]

ccfpatterns += i18n_patterns(
    path('', include('app_ccf.urls')),
)

staffpatterns = [
    path('', include('staff.urls')),
    path('ssa/', admin.site.urls),
    path('accounts/', include('admin_honeypot.urls')),
    path('mfa/', include(tf_urls)),
]

urlpatterns = [
    path('i18n/', include('django.conf.urls.i18n')),
    path('session_security/', include('session_security.urls')),
]
# Based on app type variable, set urlpatterns
if settings.APP_TYPE == 'CCF':
    urlpatterns += ccfpatterns
elif settings.APP_TYPE == 'STAFF':
    urlpatterns += staffpatterns
else:  # Local/demo have access to staff urls directly from '/staff/'
    urlpatterns += ccfpatterns
    urlpatterns += [
        path('staff/', include(staffpatterns))
    ]

# https://docs.djangoproject.com/en/dev/ref/contrib/admin/#adminsite-attributes
admin.site.site_header = 'CCF administration'
admin.site.site_title = 'CCF site admin'


if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [
        path('__debug__/', include(debug_toolbar.urls)),
    ]

staff/urls.py
from django.urls import include
from django.urls import path

from . import views

app_name = 'staff'


application_patterns = [
    path('', views.ApplicationListView.as_view(), name='ccf-application-list'),
    path('reporting/application', views.DownloadApplicationsView.as_view(), name='ccf-application-download'),
    path('<uuid:pk>/', views.ApplicationDetailView.as_view(),
         name='application-detail'),
    path('<uuid:pk>/update', views.ApplicationUpdateView.as_view(),
         name='application-update'),
]

payments_patterns = [
    path('', views.PaymentsView.as_view(), name='payments'),
    #  path('mark_as_paid/', views.MarkAsPaidView.as_view(),
    #       name='mark-as-paid'),
    path('archive/', views.PaymentsArchiveView.as_view(), name='payments-archive'),
    path('auto_process_applications/',
         views.AutoProcessApplicationsView.as_view(), name='auto-process-applications'),
    path('<str:status>/', views.DownloadReportView.as_view(), name='download-report'),
]

voucher_patterns = [
    path('', views.VoucherCodeGenerateView.as_view(), name='voucher-gen'),
    path('csv/<str:batch_id>/',
         views.DownloadVoucherCodeBatchView.as_view(), name='download-voucher'),
    path('invalidate/<str:batch_id>/', views.VoucherCodeBatchInvalidateView.as_view(),
         name='voucher-batch-invalidate'),
    path('list/', views.VoucherCodeListView.as_view(), name='voucher-list'),
    path('list/create/<str:code>',
         views.VoucherCodeListCreateApplicationRedirectView.as_view(), name='create-app-redirect'),
    path('list/invalidate/', views.VoucherCodeListInvalidateView.as_view(),
         name='voucher-list-invalidate'),
    path('list/download/', views.VoucherCodeListDownloadView.as_view(),
         name='voucher-list-download'),
]

address_patterns = [
    path('', views.PreapprovedAddressGenerateView.as_view(),
         name='address-whitelist'),
]

admin_auth_override_patterns = [
    path('password_change/', views.LoginRequiredAfterPasswordChange.as_view()),
]

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('accounts/', include(admin_auth_override_patterns)),
    path('address/', include(address_patterns)),
    path('applications/', include(application_patterns)),
    path('logout/', views.staff_logout_view, name='logout'),
    path('payments/', include(payments_patterns)),
    path('voucher/', include(voucher_patterns)),
]

staff/models.py
# -*- coding: utf-8 -*-
"""
    cash-assistance-platform.models
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

    Staff Page Data models
"""
#  from datetime import datetime
#  from datetime import timezone
#  from django.contrib.postgres.fields import JSONField
from django.db import models
from django.db.models import JSONField

from app_ccf.encoder import ApplicationEncoder
from app_ccf.models import Application


class AdminAction(models.Model):
    """
    Represents and action taken by an administrator on an Application.

    Captures the application details before and after the change.
    """
    class AdminActionType(models.TextChoices):
        """
        Represents the types of actions an admin can take to manipulate
        an application.
        """
        MANUAL_EDIT = 'manual_edit'
        AUTOMATED_FLAG = 'automated_flag'
        LAMBDA = 'lambda'

    application = models.ForeignKey(Application, on_delete=models.CASCADE)
    admin_user = models.CharField(max_length=20)
    action_dt = models.DateTimeField(auto_now_add=True)
    action_type = models.CharField(max_length=40,
                                   choices=AdminActionType.choices)
    #  text1 = models.CharField(max_length=320, default="")
    initial_app_json = JSONField(encoder=ApplicationEncoder)
    final_app_json = JSONField(encoder=ApplicationEncoder)

    @property
    def initial_app(self):
        """The Application before the action."""
        return Application(**self.initial_app_json)

    @property
    def final_app(self):
        """The Application after the action."""
        return Application(**self.final_app_json)

    @property
    def changed_fields(self):
        """The model fields that changed during the transaction.

        Returns:
            A list of 3-tuples of:
                - The field name
                - The initial value
                - The final value
        """
        changes = []
        for field in self.initial_app_json:
            initial_value = getattr(self.initial_app, field)
            final_value = getattr(self.final_app, field)
            if initial_value != final_value:
                changes.append((field, initial_value, final_value))
        return changes

app_ccf/forms.py
"""
Apllicant form components
"""
from django import forms
from django.core.exceptions import ValidationError
from django.core.validators import MaxLengthValidator
from django.forms.models import model_to_dict
from django.utils import translation
from django.utils.translation import ugettext_lazy as _
from localflavor.us.forms import USStateField
from localflavor.us.us_states import US_STATES

from .models import Application
from shared.common import clean_type_of_work_data
from shared.validation import dirty_phone_number_validator
from shared.validation import dirty_voucher_validator_v1
from shared.validation import dirty_zip_code_validator
from shared.validation import email_validator
from shared.validation import text_characters_only_validator


class ApplicationForm(forms.ModelForm):
    class Meta:
        model = Application
        fields = '__all__'


class RequirementsForm(forms.Form):
    qualified = forms.BooleanField(
        widget=forms.RadioSelect(
            choices=[
                (True, _('yes')), (False, _('no'))]))


class VoucherCheckForm(forms.Form):
    vouchercheck = forms.BooleanField(
        widget=forms.RadioSelect(
            choices=[
                (True, _('yes')), (False, _('no'))]))


class VoucherCodeForm(forms.Form):
    voucher_input = forms.CharField(
        widget=forms.TextInput(
            attrs={'class': 'form-control',
                   'maxlength': '26',  # max 20 chars + 6 dashes
                   'minlength': '9',  # min chars 9 and no dashes
                   'onkeypress': 'return isVoucherKey(event);',
                   'autocomplete': 'off'
                   }),
        validators=[dirty_voucher_validator_v1()],
    )


class ProfileForm(ApplicationForm):
    fund_name = ''

    def __init__(self, fund_name, *args, **kwargs):
        super(ProfileForm, self).__init__(*args, **kwargs)
        self.fund_name = fund_name

    first_name = forms.CharField(
        required=True,
        widget=forms.TextInput(attrs={'class': 'form-control',
                                      'maxlength': '200'}),
        validators=[text_characters_only_validator()],
    )
    last_name = forms.CharField(
        required=True,
        widget=forms.TextInput(attrs={'class': 'form-control',
                                      'maxlength': '200'}),
        validators=[text_characters_only_validator()],
    )

    class Meta:
        model = Application
        fields = ['age_range']
        widgets = {
            'age_range': forms.RadioSelect(),
        }

    def clean_age_range(self):
        data = self.cleaned_data['age_range']
        if data == Application.AgeRange.RANGE__17:
            raise forms.ValidationError(_("older_18").format(fund_name=self.fund_name))
        return data


def get_states_in(language):
    """Returns US states in the provided language, forcing eager evaluation."""
    with translation.override(language):
        return list((abbr, str(name)) for abbr, name in US_STATES[:])


class AddressForm(ApplicationForm):

    # combined all applicant info into this single form per new requirements.
    class Meta:
        model = Application
        fields = ['addr1', 'addr2', 'city', 'state', 'zip_code', 'first_name',
                  'last_name', 'phone_digits', 'email']
        widgets = {
            'addr1': forms.TextInput(attrs={'class': 'form-control'}),
            'addr2': forms.TextInput(attrs={'class': 'form-control'}),
            'city': forms.TextInput(attrs={'class': 'form-control'}),
        }

    zip_code = forms.CharField(
        widget=forms.TextInput(
            attrs={
                'class': 'form-control',
                'maxlength': '10',  # 5 digit short zip + dash + 4 digit ext
                'minlength': '5',  # 5 digit short zip
            }
        ),
        validators=[dirty_zip_code_validator()],
    )
    # Hack to deal with issue that UsStateSelect does not contain
    # a default value (https://stackoverflow.com/questions/1830894).
    state_choices = get_states_in('en')
    state_choices.insert(0, ('', _('select_one')))
    state = USStateField(widget=forms.Select(
        attrs={'class': 'form-control'}, choices=state_choices))

    # added first name and last name, phone number and email address
    first_name = forms.CharField(
        required=True,
        widget=forms.TextInput(attrs={'class': 'form-control',
                                      'maxlength': '20'}),
        validators=[text_characters_only_validator()],
    )
    last_name = forms.CharField(
        required=True,
        widget=forms.TextInput(attrs={'class': 'form-control',
                                      'maxlength': '30'}),
        validators=[text_characters_only_validator()],
    )
    phone_digits = forms.CharField(
        required=True,
        max_length=20,  # county + area + 7 digits with spaces, plus, dashes
        min_length=10,  # area + 7 digits, no country code, no special
        widget=forms.TextInput(attrs={
            'type': 'tel',
            'class': 'form-control',
            'maxlength': '20',  # county + area + 7 digits with spaces, plus, dashes
            'minlength': '10',  # area + 7 digits, no country code, no special
            'onkeypress': 'return isNumberKey(event);'
        }),
        validators=[dirty_phone_number_validator()],
    )
    email = forms.CharField(
        required=False,
        widget=forms.TextInput(attrs={
            'type': 'email',
            'class': 'form-control',
        }),
        validators=[email_validator()],
    )


class AddressVerifyForm(ApplicationForm):
    class Meta:
        model = Application
        fields = ['usps_standardized']


class TermsConditionsForm(forms.Form):
    tos = forms.BooleanField(required=True)


class EligibilityForm(ApplicationForm):
    class Meta:
        model = Application
        fields = ['signature']
        widgets = {
            'signature': forms.TextInput(attrs={'class': 'form-control'}),
        }


class ReviewForm(forms.Form):
    pass


class WelcomeForm(forms.Form):
    pass

staff/forms.py
"""
Form generators on the Staff page
"""
import django_tables2 as tables
from django.forms import ModelForm
from django.forms import Select
from django.forms import TextInput
from django.utils import translation
from django.utils.translation import ugettext_lazy as _
from django_tables2 import CheckBoxColumn
from django_tables2 import Column
from django_tables2 import TemplateColumn
from localflavor.us.forms import USStateField
from localflavor.us.us_states import US_STATES

from app_ccf.models import Application
from app_ccf.models import PreapprovedAddress
from app_ccf.models import VoucherCodeBatch


class NameColumn(Column):
    def render(self, record):
        return '{}, {}'.format(record.last_name, record.first_name)


class AddrColumn(Column):
    def render(self, record):
        return record.get_full_address()


class ApprovedApplicationTable(tables.Table):
    #  selection = CheckBoxColumn(
    #      accessor='application_id',
    #      attrs={
    #          "th__input": {
    #              "onclick": "toggle(this)"
    #          }
    #      }, orderable=False
    #  )
    name = NameColumn(order_by="last_name", verbose_name="Name", empty_values=())
    note = TemplateColumn('{{ record.note|linebreaksbr|truncatechars:150 }}')
    submitted_date = TemplateColumn('{{ record.submitted_date|date:"c" }}',
                                    attrs={"td": {"id": "submitted_dt"}}, verbose_name="Submit Date")
    status_last_modified = TemplateColumn('{{ record.status_last_modified|date:"c" }}',
                                          attrs={"td": {"id": "updated_dt"}}, verbose_name="Last Updated")
    voucher = Column(accessor="vouchercode_str", verbose_name="Code")
    affiliate = Column(accessor="vouchercode.affiliate.name", verbose_name="Affiliate", orderable=False)
    affiliate_id = Column(accessor="vouchercode.affiliate.distributor_id", verbose_name="Affiliate ID", orderable=False)
    phone = Column(accessor="phone_number", verbose_name="Phone")
    full_addr = AddrColumn(verbose_name="Address", orderable=False, empty_values=())

    class Meta:
        model = Application
        template_name = 'django_tables2/bootstrap4.html'
        #  sequence = ("selection", "name", "affiliate_id", "affiliate", "submitted_date", "status", "note", "voucher")
        sequence = ("name", "affiliate_id", "affiliate", "submitted_date", "status_last_modified", "status", "note", "voucher")
        exclude = ("first_name", "last_name", "phone_number")


def get_states_in(language):
    """Returns US states in the provided language, forcing eager evaluation."""
    with translation.override(language):
        return list((abbr, str(name)) for abbr, name in US_STATES[:])


class VoucherCodeGenerateForm(ModelForm):
    """
    Form to create voucher codes for use by applicants
    """
    class Meta:
        """
        VoucherCodeGenerateForm meta info (django)
        """
        model = VoucherCodeBatch
        fields = ['num_codes', 'affiliate', 'campaign',
                  'channel', 'base_amount', 'expiration_date']
        widgets = {
            'num_codes': TextInput(attrs={'class': 'form-control',
                                          'type': 'number', 'size': 80}),
            # TODO: change campaign to list of projects administered by BaltProm
            'campaign': TextInput(attrs={'class': 'form-control'}),
            # TODO: change channel to null or dropdown
            'channel': TextInput(attrs={'class': 'form-control'}),
            'base_amount': TextInput(attrs={'class': 'form-control',
                                            'type': 'number', 'size': 80}),
            'expiration_date': TextInput(attrs={'type': 'date',
                                                'placeholder': 'yyyy-mm-dd'}),
        }


class PreapprovedAddressGenerateForm(ModelForm):
    """
    Generate address validator form
    """
    state_choices = get_states_in('en')
    state_choices.insert(0, ('', _('select_one')))
    state = USStateField(widget=Select(
        attrs={'class': 'form-control'}, choices=state_choices))

    class Meta:
        """
        PreapprovedAddressGenerateForm meta info (django)
        """
        model = PreapprovedAddress
        fields = ['addr1', 'addr2', 'city', 'state', 'zip_code', 'note']
        widgets = {
            'addr1': TextInput(attrs={'class': 'form-control'}),
            'addr2': TextInput(attrs={'class': 'form-control'}),
            'city': TextInput(attrs={'class': 'form-control'}),
            'zip_code': TextInput(attrs={'class': 'form-control'}),
            'note': TextInput(attrs={'class': 'form-control'}),
        }

staff/templates/staff/40x.html
{% extends "base_staff.html" %}

{% block main %}
<div class="p-4 container-fluid">
{% for message in messages %}
  <p class="h3">{{ message }}</p>
{% endfor %}
</div>
{% endblock main %}

staff/templates/staff/base.html
{% load static i18n %}
<!DOCTYPE html>
<html>
  <head>
    <title>{% block title %}{% endblock %}</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    {% block head %}
    <!-- Insert Google Tag Manager -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css"
            							 integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'stylesheet.css' %}">
    {% endblock head %}
  </head>

  <body>
    <!-- Insert Google Tag Manager (noscript) -->
    <div class="main pb-4 px-4 {{ lang_code }}">
      <div class="container-fluid text-left justify-content-center pt-3 px-0">
        <div class="row justify-content-left border-bottom mb-4 pb-3">
          <div class="col media pr-0">
            <img class="ndwa-logo mr-3" src="{% static 'ndwa_en.png' %}" alt="Baltimore Responds Emergency Assistance">
            <div class="media-body mt-2 mr-1">
              <h1> <span class="coronavirus text-uppercase">{% translate 'heading_coronavirus' %} </span>
                <span class="care-fund text-uppercase"> {% translate 'heading_care_fund' %} </span>
              </h1>
            </div>
          </div>
        </div>
      </div>
      <div class="container">
        {% block content %}
        {% endblock content %}
      </div>
      <div class="push"></div>
    </div>
  </body>
</html>

staff/templates/staff/index.html
{% extends "base_staff.html" %}
{% load static i18n %}

{% block main %}
    <div class="col-5 p-4">
    </div>
    {% block content %}
    {% endblock content %}
{% endblock %}

staff/templates/staff/text_input_form.html
<div class="form-group">
  {% if title_text %}
  <label for="{{ form_field.id_for_label }}"><b>{{ title_text }}</b></label>
  {% endif %}
  {% if example_text %}
  <br/>
  <span class="text-secondary">{{ example_text }}</span>
  {% endif %}
  {{ form_field }}
</div>
{% if form_field.errors %}
<div class="alert alert-danger error-list mb-3 mt-3 ml-2 mr-2 pl-3 pr-3 pt-3 pb-3" role="alert">
  {{ form_field.errors }}
</div>
{% endif %}

staff/templates/staff/voucher_list.html
{% extends "base_staff.html" %}
{% block title %}CEAP | Staff | Voucher codes {% endblock %}
{% block sidebar-ccf-application-items %} {{block.super}}
{% endblock sidebar-ccf-application-items %}
{% load static i18n %}


{% block main %}

<div class="p-4 container-fluid">
  <!-- Invalidate code success alert -->
  {% if success %}
  <p class="alert alert-success" role="">
  Successfully invalidated
  {{ num_codes_invalidated }}
  code(s).
  </p>
  {% endif %}
  <p class="h3">{% blocktrans %}Codes{% endblocktrans %}</p>

  <!-- Code search form -->
  <style>
form          { display: table;      }
p:not(.alert) { display: table-row;  }
label         { display: table-cell; padding: 0px 10px 15px 0px ;}
input         { display: table-cell; }
  </style>
  <div class="" role="toolbar">
    <span style="padding-top: 10px">
      <form class="border p-3 col-md-12" style="display: flex;" action="" method="get" class="form">
				<div class="col-md-3" style="display: inline-block;">
					<div style="margin-left: -15px">
						{{ filter.form.as_p }}
					</div>
					<div class="row">
						<button class="btn btn-primary btn-sm btn-icon" role="submit">
							<i class="material-icons md-18">search</i>{% translate	'Search' %}
						</button>
					</div>
					{% if params_GET and not success %}
					<div class="row">
						<a
							style="color: white; margin-top: 8px;"
							class="btn btn btn-secondary btn-large text-uppercase"
							onclick="downloadCodes()"
							>
							{% translate	'Download Filtered' %}
						</a>
						<div id="working" style="margin-left: 8px; align-self: center; display: none;" class="spinner-border text-info "></div>
					</div>
					{% endif %}
				</div>
				<div class="col-md-9" style="display: inline-block; flex-align: stretch;">
					<table class="table table-hover mt-4">
						<thead>
							<tr>
								<th scope="col">ID</th>
								<th scope="col">{% translate  'Affiliate' %}</th>
								<th scope="col">ID</th>
								<th scope="col">{% translate  'Affiliate' %}</th>
								<th scope="col">ID</th>
								<th scope="col">{% translate  'Affiliate' %}</th>
							</tr>
						</thead>
						<tbody>
							<tr>
								<td>802123</td><td>Bon Secours Community Works</td>
								<td>802124</td><td><div>Banner Neighborhoods</div> Community Corporation</td>
								<td>802125</td><td>CASA of Maryland, Inc.</td>
							</tr>
							<tr>
								<td>802126</td><td>Center for Urban Families</td>
								<td>802127</td><td>City of Refuge Baltimore</td>
								<td>802128</td><td>Elev8</td>
							</tr>
							<tr>
								<td>802130</td><td>Esperanza Center</td>
								<td>802131</td><td>Urban Strategies Baltimore</td>
								<td>802132</td><td>Job Opportunities Task Force</td>
							</tr>
							<tr>
								<td>802133</td><td>Historic East Baltimore Community Action Coalition</td>
								<td>802134</td><td>Safe Streets – Park Heights</td>
								<td>802135</td><td>Safe Streets – Cherry Hill</td>
							</tr>
							<tr>
								<td>802136</td><td>Center for Urban Families</td>
								<td></td><td></td>
							</tr>
						</tbody>
					</table>
				</div>
      </form>
    </span>
  </div>

  <!-- Number of codes found (+ invalidate button if a search was submitted) -->
  <div>
    <p>
    <br />
    {% if params_GET and not success %}
    Showing <b>{{ object_list | length }}</b> code{{ object_list|length|pluralize:"s" }} of out <b>{{ filter.qs | length }}</b>.
    <button style="margin-left: 8px;" class="btn btn btn-danger btn-large text-uppercase" id="invalidate" role="submit">
      {% translate  'Invalidate' %}
    </button>
    {% else %}
    Total of <b>{{ filter.qs | length }}</b> code{{ object_list|length|pluralize:"s" }} found.
    {% endif %}
    </p>
  </div>

  <!-- Code search results -->
  <div>
    <table class="table table-hover mt-4">
      <thead>
        <tr>
          <th scope="col">{% translate  'Code' %}</th>
          <th scope="col">{% translate  'Channel' %}</th>
          <th scope="col">{% translate  'Affiliate' %} ID</th>
          <th scope="col">{% translate  'Affiliate' %}</th>
          <th scope="col">{% translate  'Campaign' %}</th>
          <th scope="col">{% translate  'Amount' %}</th>
          <th scope="col">{% translate  'Created' %}</th>
          <th scope="col">{% translate  'Expires' %}</th>
          <th scope="col">{% translate  'Application' %}</th>
        </tr>
      </thead>
      <tbody>
        {% for voucher_code in object_list %}
        <tr>
          <td>{{ voucher_code.code }}</td>
          <td>{{ voucher_code.batch.channel }}</td>
          <td>{{ voucher_code.batch.affiliate.distributor_id }}</td>
          <td>{{ voucher_code.batch.affiliate.name }}</td>
          <td>{{ voucher_code.batch.campaign }}</td>
          <td>{{ voucher_code.amount }}</td>
          <td id="create_dt">{{ voucher_code.batch.created|date:"c" }}</td>
          <td id="expire_dt">{{ voucher_code.batch.expiration_date|date:"c" }}</td>
          {% if voucher_code.application_id %}
          <td><a href="{% url 'staff:application-detail' voucher_code.application_id %}">
							{{ voucher_code.application.last_name }}, {{ voucher_code.application.first_name }}
						</a></td>
						{% else %}
						<td><a href="{% url 'staff:create-app-redirect' voucher_code.code_formatted %}" target="_blank">
								Create <i class="material-icons md-18">launch</i>
							</a></td>
							{% endif %}
        </tr>
        {% endfor %}
      </tbody>
    </table>
		{% include 'staff/snippets/pagination.html' with object_list=object_list%}
  </div>
</div>

<!-- Invalidate confirmation modal -->
<div class="modal" id="voucher-invalidate-mdl" tabindex="-1" role="dialog">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        Review
      </div>
      <div class="modal-body">

        <p>
        Are you sure you want to invalidate the
        <b><span id="num_codes" style="white-space: pre-wrap;"></span></b>
        code(s) from this search?
        </p>
        <br/>

        <form action="{% url 'staff:voucher-list-invalidate' %}" style="display:block;margin-bottom: 10px" method="post">
          {% csrf_token %}
          <button type="submit" class="btn btn-danger btn-block btn-large text-uppercase" name='submit-invalidate' value='{{ code_list }}'>Invalidate</button>
        </form>
        <button type="button" class="btn btn-outline-secondary btn-block btn-large text-uppercase" data-dismiss="modal">
          Cancel
        </button>
      </div>
    </div>
  </div>
</div>
<!-- Button setup scripts -->
<script>
  // Set up confirmation modal when invalidate is clicked
  $('#invalidate').attr('type', 'button');
		$('#invalidate').click(function() {
				$('#voucher-invalidate-mdl').modal('show');
				$('#num_codes').text('{{ filter.qs | length }}');
				$('#confirm-btn').click(function() {
						$('#voucher_form').submit();
					});
			});
</script>
<script>
  function downloadCodes(code_ids) {
  		$("#working").show()
			$.ajaxSetup({
					beforeSend: function (xhr) {
							xhr.setRequestHeader('X-CSRFToken', '{{ csrf_token }}');
						}
				});
			$.ajax({
					type: 'get',
					url: `download${window.location.search}`,
					timeout: 0,
					success: function (response) {
							$("#working").hide()
							// Save the response as a CSV file
							const downloadLink = document.createElement("a");
							const blob = new Blob([response]);
							const url = URL.createObjectURL(blob);
							downloadLink.href = url;
							downloadLink.download =
								`filteredCodes_${dayjs(new Date()).format('YYYY-MM-DD_HH-mm-ss')}.csv`;
							document.body.appendChild(downloadLink);
							downloadLink.click();
							document.body.removeChild(downloadLink);
						},
					error: function (e) {
							console.error(e);
							$("#working").hide()
						}
				})
		}
</script>
<script>
	window.onload = function() { $("td[id*='dt']").each(function() { $(this).text(formatDay($(this).text())) }); }
		function formatDay(dateString) { return dayjs(dateString).format('MMM DD, YYYY h:mm A') }
</script>
{% endblock main %}